with:
    # ... other options
    plugin_habits: yes
    plugin_habits_from: 200       # Use 200 events to compute habits
    plugin_habits_days: 14        # Keep only events from last 14 days
    plugin_habits_facts: yes      # Display facts section
    plugin_habits_charts: yes     # Display charts section
    config_timezone: Europe/Paris # Set timezone
