name: Stars and Forks Stats

on:
  fork:
  watch:
    types:
      - started
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Stars and Forks Description Update
        uses: ouuan/This-repo-has-x-stars-y-forks-action@v2
        with:
          token: ${{ secrets.STAR_FORK_TOKEN }}
          template: "⭐ <starCount>. You found a secret!"
